### ISSUE TITLE
use soot API analysis java source code error

### ISSUE THREAD

**Issue by SQLKILL** [soot-oss/soot#1377] opened 2020-07-02 10:26 UTC
I use gradle to build soot to analyze the java source code, but the following error occurs every time. The versions I use are all 2.7.1, including **soot-infoflow: 2.7.1, soot-infoflow-android: 2.7.1, soot-infoflow-cmd: 2.7.1, soot-infoflow-summaries: 2.7.1**. As long as the source code contains ArrayList objects or print statements, errors will occur. How can I avoid this error? Can I only use bytecode files? What should I do if I can only use the source code?

`
Exception in thread "main" java.lang.Error: Error: Failed to load java.lang.CharSequence.
	at soot.JastAddJ.PathPart.getCompilationUnit(PathPart.java:109)
	at soot.JastAddJ.Program.getCompilationUnit(Program.java:873)
	at soot.JastAddJ.Program.getLibCompilationUnit_compute(Program.java:1517)
	at soot.JastAddJ.Program.getLibCompilationUnit(Program.java:1500)
	at soot.JastAddJ.Program.lookupLibType_compute(Program.java:1465)
	at soot.JastAddJ.Program.lookupLibType(Program.java:1433)
	at soot.JastAddJ.Program.lookupType_compute(Program.java:1412)
	at soot.JastAddJ.Program.lookupType(Program.java:1393)
	at soot.JastAddJ.Program.Define_TypeDecl_lookupType(Program.java:1981)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.Expr.lookupType(Expr.java:1186)
	at soot.JastAddJ.TypeAccess.decls_compute(TypeAccess.java:425)
	at soot.JastAddJ.TypeAccess.decls(TypeAccess.java:414)
	at soot.JastAddJ.TypeAccess.refined_TypeScopePropagation_TypeAccess_decl(TypeAccess.java:387)
	at soot.JastAddJ.TypeAccess.decl_compute(TypeAccess.java:460)
	at soot.JastAddJ.TypeAccess.decl(TypeAccess.java:452)
	at soot.JastAddJ.TypeAccess.type_compute(TypeAccess.java:590)
	at soot.JastAddJ.TypeAccess.type(TypeAccess.java:583)
	at soot.JastAddJ.ClassDecl.isCircular_compute(ClassDecl.java:1696)
	at soot.JastAddJ.ClassDecl.isCircular(ClassDecl.java:1673)
	at soot.JastAddJ.ClassDecl.superclass(ClassDecl.java:240)
	at soot.JastAddJ.ClassDecl.supertypeClassDecl(ClassDecl.java:1841)
	at soot.JastAddJ.ClassDecl.subtype_compute(ClassDecl.java:1832)
	at soot.JastAddJ.ClassDecl.subtype(ClassDecl.java:1817)
	at soot.JastAddJ.TypeVariable.supertypeClassDecl(TypeVariable.java:1414)
	at soot.JastAddJ.ClassDecl.subtype_compute(ClassDecl.java:1832)
	at soot.JastAddJ.ClassDecl.subtype(ClassDecl.java:1796)
	at soot.JastAddJ.ClassDecl.instanceOf_compute(ClassDecl.java:1555)
	at soot.JastAddJ.ClassDecl.instanceOf(ClassDecl.java:1548)
	at soot.JastAddJ.ParTypeAccess.typeCheck(ParTypeAccess.java:121)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1284)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.CompilationUnit.errorCheck(CompilationUnit.java:178)
	at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:67)
	at soot.JavaClassSource.resolve(JavaClassSource.java:66)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:240)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:214)
	at soot.SootResolver.bringToSignatures(SootResolver.java:279)
	at soot.SootResolver.bringToBodies(SootResolver.java:319)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:164)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.loadClass(Scene.java:942)
	at soot.Scene.loadClassAndSupport(Scene.java:927)
	at soot.Scene.loadNecessaryClasses(Scene.java:1753)
	at CallGraphTest.main(CallGraphTest.java:26)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 20492
Caused by: java.lang.ArrayIndexOutOfBoundsException: 20492
	at soot.JastAddJ.BytecodeParser.parseThisClass(BytecodeParser.java:437)
	at soot.JastAddJ.BytecodeParser.parseTypeDecl(BytecodeParser.java:413)
	at soot.JastAddJ.BytecodeParser.parse(BytecodeParser.java:331)
	at soot.JastAddJ.BytecodeParser.read(BytecodeParser.java:27)
	at soot.JastAddJ.PathPart.getCompilationUnit(PathPart.java:87)
	... 56 more
`

**Comment by SQLKILL** [comment] 2020-07-02 10:28
**The java version I use is 1.8.0_241**

**Comment by SQLKILL** [comment] 2020-07-02 13:58
I changed the version of soot to 4.2.0, this error still occurs, what should I do

**Comment by ericbodden** [comment] 2020-07-03 11:40
Hi. I believe this to be a bug in Soot. I am afraid, however, that right now we have limited capacity to fix the source-code frontend. We are in the process of building a new one but that will need some more time before we can release it.

We are happy to accept a patch if you can provide one!

Other than that I can unfortunately just recommend that you try analyzing bytecode instead. That should be more stable.

**Comment by SQLKILL** [comment] 2020-07-06 01:56
> Hi. I believe this to be a bug in Soot. I am afraid, however, that right now we have limited capacity to fix the source-code frontend. We are in the process of building a new one but that will need some more time before we can release it.
> 
> We are happy to accept a patch if you can provide one!
> 
> Other than that I can unfortunately just recommend that you try analyzing bytecode instead. That should be more stable.

Thanks，Can you provide some ideas to solve this problem? If I want to fix this bug, where should I start?

**Comment by ericbodden** [comment] 2020-07-06 07:27
In the past when I had to debug similar problems, I would run Soot in a debugger such that I could reliably reproduce the problem. Then, from the error message, I would try to track back during the execution until I would be able to find the root cause of the problem. I hope this helps.

**Comment by BACMiao** [comment] 2020-07-17 07:15
> In the past when I had to debug similar problems, I would run Soot in a debugger such that I could reliably reproduce the problem. Then, from the error message, I would try to track back during the execution until I would be able to find the root cause of the problem. I hope this helps.

The issue #1377 will occur, because the analysis the source-code frontend using the constant pool in bytecode with java6. Howerer, three more constant categories have been added to the constant pool in bytecode after java7. Parsing java.lang.CharSequence failed，because original code unknown the tag 15/16/18 in the constant pool. I have  provided a pull request to fix this issue.

**Comment by BACMiao** [comment] 2020-07-17 08:49
> In the past when I had to debug similar problems, I would run Soot in a debugger such that I could reliably reproduce the problem. Then, from the error message, I would try to track back during the execution until I would be able to find the root cause of the problem. I hope this helps.

Thanks for you help.

**Comment by mbenz89** [comment] 2020-07-17 09:37
Fixed by #1384. Thanks for providing a PR for this issue!

**Closed by mbenz89** 2020-07-17 09:37 UTC
