### ISSUE TITLE
OutOfMemoryError for a simple (but invalid) class file

### ISSUE THREAD

**Issue by ericbodden** [soot-oss/soot#1470] opened 2020-10-15 17:30 UTC
Soot runs out of memory when processing this class file. The appropriate command line is simply:
`soot.Main --allow-phantom-refs --process-dir classes` where `classes` contains the class in this archive...
[ProcessingStatistics$ProcessingStatisticsBuilder.class.zip](https://github.com/soot-oss/soot/files/5386700/ProcessingStatistics.ProcessingStatisticsBuilder.class.zip)

The class seems broken: the build() method reads from uninitialized fields of an objects whose initializer is called only at the end of the same method. Yet, Soot should recognize this and handle this gracefully.

The problem seems to reside somewhere in AsmMethodSource.

**Comment by linghuiluo** [comment] 2020-10-16 18:26
@ericbodden  Martin told me about this. This happens very often on Exception classes 
   
```

    NEW java/lang/IllegalArgumentException
    DUP
    NEW java/lang/StringBuilder
    DUP
    INVOKESPECIAL java/lang/StringBuilder.<init> ()V
    LDC "Element for "
    INVOKEVIRTUAL java/lang/StringBuilder.append (Ljava/lang/String;)Ljava/lang/StringBuilder;
    ALOAD 1
    INVOKEVIRTUAL java/lang/StringBuilder.append (Ljava/lang/String;)Ljava/lang/StringBuilder;
    LDC " is not an Application ("
    INVOKEVIRTUAL java/lang/StringBuilder.append (Ljava/lang/String;)Ljava/lang/StringBuilder;
    ALOAD 2
    INVOKEVIRTUAL java/lang/StringBuilder.append (Ljava/lang/Object;)Ljava/lang/StringBuilder;
    LDC ")"
    INVOKEVIRTUAL java/lang/StringBuilder.append (Ljava/lang/String;)Ljava/lang/StringBuilder;
    INVOKEVIRTUAL java/lang/StringBuilder.toString ()Ljava/lang/String;
    INVOKESPECIAL java/lang/IllegalArgumentException.<init> (Ljava/lang/String;)V
    ATHROW


 NEW org/apache/brooklyn/util/exceptions/UserFacingException
    DUP
    NEW java/lang/StringBuilder
    DUP
    INVOKESPECIAL java/lang/StringBuilder.<init> ()V
    LDC "Illegal parameter for 'location'; must be a string or map (but got "
    INVOKEVIRTUAL java/lang/StringBuilder.append (Ljava/lang/String;)Ljava/lang/StringBuilder;
    ALOAD 3
    INVOKEVIRTUAL java/lang/StringBuilder.append (Ljava/lang/Object;)Ljava/lang/StringBuilder;
    LDC ")"
    INVOKEVIRTUAL java/lang/StringBuilder.append (Ljava/lang/String;)Ljava/lang/StringBuilder;
    INVOKEVIRTUAL java/lang/StringBuilder.toString ()Ljava/lang/String;
    INVOKESPECIAL org/apache/brooklyn/util/exceptions/UserFacingException.<init> (Ljava/lang/String;)V
    ATHROW

```

**Comment by linghuiluo** [comment] 2020-10-16 18:31
I dont think it is caused by the initializer

**Comment by linghuiluo** [comment] 2020-10-16 19:13
After debugging into this issue. I think the root cause is in the method `AsmMethodSource.void mergeUnits(AbstractInsnNode insn, Unit u) 
`


`
    void mergeUnits(AbstractInsnNode insn, Unit u) {
        Unit prev = (Unit)this.units.put(insn, u);
        if (prev != null) {
            Unit merged = new UnitContainer(new Unit[]{prev, u});
            this.units.put(insn, merged);
        }

    }
`
This method doesn't check if prev is equal to u. when it is the case, it creates a recursive UnitContainer (see screenshot below). This recursive UnitContainer will later cause AsmMethodSource.emitUnit to throw stack-overflow exception 

```
    private void emitUnits(Unit u) {
        if (u instanceof UnitContainer) {
            Unit[] var2 = ((UnitContainer)u).units;
            int var3 = var2.length;

            for(int var4 = 0; var4 < var3; ++var4) {
                Unit uu = var2[var4];
                this.emitUnits(uu); 
            }
        } else {
            this.body.getUnits().add(u);
        }
```
<img width="1281" alt="Screenshot 2020-10-16 at 21 12 25" src="https://user-images.githubusercontent.com/18470909/96299408-5193a700-0ff4-11eb-8633-7be55f2ea40e.png">

**Comment by StevenArzt** [comment] 2020-10-19 07:33
Thank you for your contribution. Great work!

**Closed by StevenArzt** 2020-10-19 07:33 UTC
Labels: bug, enhancement, good first issue
